##############################################################################
# Firmware Source
##############################################################################

device_port: /dev/ttyUSB0

left_wheel_joint: left_wheel

right_wheel_joint: right_wheel

odom_frame: odom

base_frame: base_link
